name: Deploy Backend
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Chá»‰ cháº¡y khi báº¡n sá»­a code trong thÆ° má»¥c backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Láº¥y code tá»« GitHub
        uses: actions/checkout@v4

      - name: ğŸš€ Äáº©y code lÃªn InfinityFree (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Láº¥y code tá»« thÆ° má»¥c nÃ y trÃªn GitHub
          local-dir: ./backend/
          
          # Äáº©y vÃ o thÆ° má»¥c nÃ y trÃªn Host
          server-dir: htdocs/web-be/
          
          # Bá» qua file rÃ¡c
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
