name: Deploy Frontend
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Chá»‰ cháº¡y khi báº¡n sá»­a code trong thÆ° má»¥c frontend

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Láº¥y code tá»« GitHub
        uses: actions/checkout@v4

      - name: ğŸš€ Äáº©y code lÃªn InfinityFree (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Láº¥y code tá»« thÆ° má»¥c nÃ y trÃªn GitHub
          local-dir: ./frontend/
          
          # Äáº©y vÃ o thÆ° má»¥c nÃ y trÃªn Host (InfinityFree báº¯t buá»™c pháº£i cÃ³ htdocs)
          server-dir: htdocs/web-fe/
          
          # Bá» qua file rÃ¡c khÃ´ng cáº§n Ä‘áº©y lÃªn (cho nháº¹ host)
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
